### ISSUE TITLE
Add support of automatically configuring the OILauncher

### ISSUE THREAD

**Issue by bnicholesdell** [OneIdentity/RemoteApplicationPublisher#19]
Add a checkbox to the application configuration dialog to launch with IOLauncher.  That would automatically put the OILauncher into the application path and construct the command line parameters with the application that was selected.  It would also add the injectable parameters for the application and allow the user to edit just the command line.  It would also set the command line options to enforced.

**Comment by petrsnd** [comment]
1.0.1 has this feature
